tools:
  external_code_coverage: true
  php_sim: true
  php_pdepend: true
  php_analyzer: true
checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: [src/*]
    excluded_paths: [src/Transform/AppBundle/Tests/*]
