language: php

php:
  - 5.5

before_script:
  - make composer.install

script:
  - make test.run

after_script:
  - make scrutinizer.coverage

after_success:
  - make build.package

branches:
  except:
    - /^build-[0-9a-z\-]*/

notifications:
  slack: $NOTIFICATION

env:
  global:
    - secure: "SGGDETOkl7xHWy1NnzTO9vnO0mDWztpWu7faukEW1/wVWVUzzLcLzG0yUhMgty89VE9/SKxK9r6abpesd+qyuFLssqIkqW9XW5u2k6StSNVnDnMvvYReH1KpceRbrH+axy6rzw+asf7u25A3dvd3ia3v0tg2IWhnJCbquRiZkNA="
    - secure: "MDwkP+UzF/nQYROvWL5sgvZLVjqViuLt+IO2+ja8NiyWqnI2tKReaLsv23hPsS3zUvYhH9MSRCezR1um9aIxLqzxiU6x2z0xh1qCWzMvcONfF3NeuLu6EnWBf0365ppgnCNvzPPR/N0SMkWfkubYfWWX1mtRpateep23RWHVA+c="
