language: php

php:
  - 5.5

before_script:
  - make composer.install

script:
  - make test.run

after_script:
  - make scrutinizer.coverage

after_success:
  - make build.package

after_failure:
  - make logs

branches:
  except:
    - /^build-[0-9a-z\-]*/

notifications:
  slack:
    secure: YdsXHqZ3S9gkBsC92vsjN2qw/bGwYYxuoDPHqTx+37yt8sIbNhaT72nUQIO9nzzmZVOVNbg/oN2IErV5AL3oLWxTROcZT8AMnHzV5AM05epXlXPV0dugY5l+UUPztTJooTStj4oPrrjXQf8jxaKVL++uRX7AmRxDnTDvGclI5/w=

env:
  global:
    - secure: SGGDETOkl7xHWy1NnzTO9vnO0mDWztpWu7faukEW1/wVWVUzzLcLzG0yUhMgty89VE9/SKxK9r6abpesd+qyuFLssqIkqW9XW5u2k6StSNVnDnMvvYReH1KpceRbrH+axy6rzw+asf7u25A3dvd3ia3v0tg2IWhnJCbquRiZkNA=

deploy:
  provider: heroku
  buildpack: https://github.com/eddiejaoude/heroku-buildpack-php-dev#master
  api_key:
    secure: ZI+ZGOlnq5/ThMbOh3h/EgQqMILxjxyJB90jY1AdTbPRh4qC9ZzLq4wGAKJOqOO3TF0UyjuEEIyrxVypVQ27dllYvXt2pa7JU79yQpbFkWxa/B9o6lscjdRJ3Zm/6Lie1/mF2P0uwoGLRFXi7y6R5m2aY+NJ9IEvxyJiOfygMV0=
  app: dial-tone-frontend
  on:
    all_branches: true