language: php

php:
  - 5.5

before_script:
  - make composer.install

script:
  - make test.run

after_script:
  - make scrutinizer.coverage

after_success:
  - make build.package

branches:
  except:
    - /^build-[0-9a-z\-]*/

env:
  global:
    - secure: "RCTrTVKciTmOPjSSLUwcCrsKZdKjw2tRUJEuwaOAmH/dLT4DRwyWg5+OJNin9napEcf+F96QFGSgfzoFnMvIg0rp1Bp4IPkIwBu+8fdIOQQApEEAPDg5jDCxzl17m0NPxGS6Pmv4u+OD+xyAkA24FjDk3ZUq1clFhX3LXINFRlk="
