transform_core_app_changelog:
    path:     /changelog
    defaults: { _controller: TransformCoreAppBundle:Default:changelog }

transform_core_app_homepage:
    path:     /hello/{name}
    defaults: { _controller: TransformCoreAppBundle:Default:index }
